'use client';

import Link from 'next/link';
import { ArrowLeft, Send, ShieldCheck, Globe, Cookie } from 'lucide-react';
import CSRFVisualizer from '@/components/visualizations/CSRFVisualizer';
import { motion } from 'framer-motion';

export default function CSRFPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-white selection:bg-pink-500 selection:text-white pb-20">
      <div className="container mx-auto px-4 py-8">
        <Link href="/" className="inline-flex items-center text-slate-400 hover:text-white transition-colors mb-8">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Atlas
        </Link>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <div className="mb-12">
            <h1 className="text-5xl font-bold mb-4 text-pink-500">
              Cross-Site Request Forgery (CSRF)
            </h1>
            <p className="text-xl text-slate-400 max-w-3xl">
              CSRF is an attack that tricks a victim into submitting a malicious request. It inherits the identity and privileges of the victim to perform an undesired function on their behalf.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 mb-20">
            <div>
              <h2 className="text-2xl font-bold mb-6 flex items-center">
                <Send className="w-6 h-6 mr-2 text-pink-500" />
                Attack Simulation
              </h2>
              <CSRFVisualizer />
              <p className="mt-4 text-sm text-slate-500 italic">
                Interactive: Switch between tabs. Make sure you are "Logged In" to the bank, then visit the Malicious site and click the button. Check your bank balance afterwards.
              </p>
            </div>

            <div className="space-y-8">
              <div className="bg-slate-900/50 p-6 rounded-xl border border-slate-800">
                <h3 className="text-xl font-bold mb-4 text-cyan-400 flex items-center">
                  <Cookie className="w-5 h-5 mr-2" />
                  The Mechanism
                </h3>
                <ul className="space-y-4 text-slate-300">
                  <li className="flex items-start">
                    <span className="bg-slate-800 px-2 py-1 rounded text-xs font-mono mr-3 mt-1 text-cyan-500">Trust</span>
                    <span>Browsers automatically include session cookies with every request to a domain, even if the request originated from a different site.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="bg-slate-800 px-2 py-1 rounded text-xs font-mono mr-3 mt-1 text-cyan-500">Deception</span>
                    <span>The attacker creates a link or form (like a "Claim Prize" button) that actually points to `bank.com/transfer`.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="bg-slate-800 px-2 py-1 rounded text-xs font-mono mr-3 mt-1 text-cyan-500">Execution</span>
                    <span>If the user is logged in, the bank accepts the request because it includes the valid session cookie.</span>
                  </li>
                </ul>
              </div>

              <div className="bg-slate-900/50 p-6 rounded-xl border border-slate-800">
                <h3 className="text-xl font-bold mb-4 text-green-400 flex items-center">
                  <ShieldCheck className="w-5 h-5 mr-2" />
                  Prevention & Defense
                </h3>
                <div className="space-y-4">
                  <div className="flex items-start">
                    <div className="w-2 h-2 mt-2 rounded-full bg-green-500 mr-3 shrink-0" />
                    <div>
                      <span className="font-bold block text-slate-200">Anti-CSRF Tokens</span>
                      <span className="text-slate-400 text-sm">A unique, random token generated by the server and checked with every state-changing request. The attacker's site can't guess this token.</span>
                    </div>
                  </div>
                  <div className="flex items-start">
                    <div className="w-2 h-2 mt-2 rounded-full bg-green-500 mr-3 shrink-0" />
                    <div>
                      <span className="font-bold block text-slate-200">SameSite Cookie Attribute</span>
                      <span className="text-slate-400 text-sm">Setting cookies to `SameSite=Strict` or `Lax` tells the browser not to send the cookie with cross-site requests.</span>
                    </div>
                  </div>
                  <div className="flex items-start">
                    <div className="w-2 h-2 mt-2 rounded-full bg-green-500 mr-3 shrink-0" />
                    <div>
                      <span className="font-bold block text-slate-200">Re-Authentication</span>
                      <span className="text-slate-400 text-sm">Asking for the password again before sensitive actions (like changing a password or transferring money).</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </main>
  );
}

